name: Build & Release

on:
  push:
    branches: ["main"]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # required for changelog generation

      - name: Setup JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "corretto"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          gradle-version: '9.7.0'
          cache-provider: basic

      - name: Get version
        id: version
        run: |
          VERSION=$(grep '^version=' gradle.properties | cut -d '=' -f2)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if tag exists
        id: tag_check
        run: |
          if git ls-remote --tags origin "refs/tags/v${{ steps.version.outputs.VERSION }}" | grep -q .; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Build
        if: steps.tag_check.outputs.exists == 'false'
        run: ./gradlew build --parallel --build-cache

      - name: Create tag
        if: steps.tag_check.outputs.exists == 'false'
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git tag "v${{ steps.version.outputs.VERSION }}"
          git push origin "v${{ steps.version.outputs.VERSION }}"

      - name: Generate changelog
        if: steps.tag_check.outputs.exists == 'false'
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v6
        with:
          mode: "COMMIT"
          configurationJson: |
            {
              "template": "#{{CHANGELOG}}",
              "categories": [
                { "title": "## 🚀 Features",  "labels": ["feat", "feature"] },
                { "title": "## 🐛 Fixes",     "labels": ["fix", "bug"] },
                { "title": "## 🔧 Other",     "labels": [] }
              ],
              "label_extractor": [
                {
                  "pattern": "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\\([\\w\\-\\.]+\\))?(!)?: ([\\w ])+([\\s\\S]*)",
                  "on_property": "title",
                  "target": "$1"
                }
              ]
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        if: steps.tag_check.outputs.exists == 'false'
        uses: softprops/action-gh-release@v3
        with:
          tag_name: "v${{ steps.version.outputs.VERSION }}"
          name: "Release v${{ steps.version.outputs.VERSION }}"
          body: ${{ steps.changelog.outputs.changelog }}
          files: |
            configurate/build/libs/*.jar
            build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}